### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by bgruening** [CRG-Barcelona/bwtool#44]
We are trying to integrate bwtool into Galaxy https://github.com/galaxyproject/tools-iuc/compare/bwtool?expand=1, but unfortunately the latest [release](https://github.com/CRG-Barcelona/bwtool/releases/tag/v1.0-gamma) is crashing for every huge bigwig file. Compiling from master seems to work and a new release would make our life much easier. 

Thanks,
Bjoern

**Comment by andypohl** [comment]
Yes, I'm sorry.  I haven't been utilizing releases very formally.  I think the release you took was after a tidy commit, but I was more/less experimenting with github features.  I think the master you took is probably more relevant.  The code's been in stasis for a while, so a release to reflect what probably most people have is a good idea.  I'll try doing this soon.

**Comment by bgruening** [comment]
Awesome! You packed your lib so nicely into the release to it's really easy to install from this release and quite complicated to compile from master. 
My aim is to put this into the Galaxy Tool Shed so installation will be handled automatically for all users.

Thanks,
Bjoern

**Comment by andypohl** [comment]
Yes if bwtool was the only program using the library, I'd have kept it in there, but it needed to be separated to avoid repetition in the packaging of other programs.  But the classic three-command installation is indeed missed.  One way to get around this is to maybe make another repository to have a program called "bwtool-install", that essentially pulls from the two repositories.  I don't think anything like this would happen though until I transitioned from autotools to cmake, which I've been planning for a while.  cmake would make a lot of things easier: including making shared libraries and making pre-built binaries packaged for linux package managers like RPM and apt-get.

**Comment by bgruening** [comment]
Maybe this can work as well? http://www.git-scm.com/book/en/v2/Git-Tools-Submodules

A release like the last one would be enough for us at the moment :)

**Comment by bgruening** [comment]
@andypohl thanks for the release! Any chance to get also the lib into the tarball? This would make installation way easier in Galaxy.

**Comment by andypohl** [comment]
Right, sorry for the delayed response.  Let me confess I haven't put much time into it, but while I was working on a solution for this, I was still struggling with a strategy.  I think I've settled with the following:

1. This unified build will be a specific branch of bwtool.  I'll take your idea of putting the submodule.   It's still important to me to have the library separated, because from an engineering standpoint it's a lot more elegant, plus to my knowledge it's the only standalone (nearly standalone) example of the Kent/UCSC C library available.  I have plans to implement an API or packages from other languages e.g. Python or R.
2. I'll postpone the cmake transition for a while.  I'll go back to the earlier release to see the original configure.ac and Makefile.am and adapt that to whatever newer files, etc have come in since.

**Comment by andypohl** [comment]
I've unified things into a new repository called bwtool-ue ("unified edition").  I am fighting with the Makefiles a bit, but I think I'll have something soon.

**Comment by andypohl** [comment]
Go check out [bwtool-ue](https://github.com/andypohl/bwtool-ue).  Everything seems to compile on my computer.  Please let me know if you have problems.  I should note that one of your original requests was to have a versioned release.  Unfortunately, I've hit a limitation with GitHub regarding this.  It looks like I'm unable to package submodules with the main repository.  And note that if you want to get all the code you need to build bwtool, you'll need the --recursive option with git clone:

```
git clone --recursive https://github.com/andypohl/bwtool-ue.git
cd bwtool-ue/
./configure
make
sudo make install
```
I'm sorry if that isn't good enough.  I can certainly make a tarball myself, but I don't know how to make github make it.

**Comment by andypohl** [comment]
Alright, I made tarball/zipfiles myself and added them to the release:
https://github.com/andypohl/bwtool-ue/releases/tag/1.0

**Comment by bgruening** [comment]
@andypohl awesome! I will work further on Galaxy integration now! Thanks a lot!

**Comment by andypohl** [comment]
It might interest you that I have an automated Docker build from this bwtool-ue repository:
https://registry.hub.docker.com/u/andypohl/bwtool-ue/

If you have docker installed, running bwtool should be as easy as:

    docker run --rm andypohl/bwtool-ue 

Updates to the bwtool-ue repository should trigger a new docker image build.

**Comment by bgruening** [comment]
Yes indeed, thanks!

**Comment by andypohl** [comment]
Is everything going ok?

**Comment by bgruening** [comment]
I think so https://github.com/galaxyproject/tools-iuc/pull/255
Still a lot todo, but progressing.

Thanks @andypohl!

**Comment by hengbingao** [comment]
the bwtool-ue may can not be found
