### ISSUE TITLE
Trying to install bwtool but there is something wrong with the binary_format() 

### ISSUE THREAD

**Issue by yfu** [CRG-Barcelona/bwtool#46]
It seems that bwtools is not compatible with the function binary_format() in /usr/local/include/htslib/hts.h. How can I solve it?

```Making install in beato
make[1]: Entering directory `/home/user/repo/tools/libbeato/beato'
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -fno-strict-aliasing -g -O0 -I/home/user/include -MT metaBigBam.o -MD -MP -MF .deps/metaBigBam.Tpo -c -o metaBigBam.o metaBigBam.c
metaBigBam.c:572:13: error: ‘binary_format’ redeclared as different kind of symbol
 static void binary_format(char *s, int num)
             ^
In file included from /usr/local/include/htslib/sam.h:30:0,
                 from ../beato/metaBig.h:20,
                 from metaBigBam.c:16:
/usr/local/include/htslib/hts.h:86:5: note: previous definition of ‘binary_format’ was here
     binary_format, text_format,
     ^
make[1]: *** [metaBigBam.o] Error 1
```

**Comment by andypohl** [comment]
Sorry I haven't seen this one yet.  My guess at the moment is that the HTS library has been updated and bwtool needs to be updated accordingly.  It doesn't look like a difficult problem to fix.  I think maybe some function needs renaming so to avoid a clash in the name space.  Sorry, I just happen to be on vacation, but I might still be able to fix this tomorrow.

**Comment by yfu** [comment]
Thanks for your reply! I was compiling it with the newest htslib (1.2). Is it possible to compile bwtool with the old HTS library? If so, how? It would be much better if you can fix function names!

Thanks!
Yu

**Comment by andypohl** [comment]
Yes, it's possible to do that but I think it's better to fix it on this end.  I checked in a fix to CRG-Barcelona/libbeato.  You will want to git pull and try making again.  I was able to reproduce this compile error with a fresh install of HTS lib.

**Comment by yfu** [comment]
It now works! Thanks very much!
