### ISSUE TITLE
bwtool agg crashes on ERCC spike-in sequences

### ISSUE THREAD

**Issue by julienlag** [CRG-Barcelona/bwtool#53]
Hey Andy,
i'm trying to run "bwtool agg" on ERCC spike-in sequences but it crashes. ERCC spike-ins are a set of 92 synthetic, unspliced sequences that one adds to an RNA mix before making a cDNA library.  Conceptually, I guess each of those 92 sequences could be considered a separate chromosome. Their sequences are known, so one can map RNAseq reads onto them and generate BigWigs.

Here's the command I've used, followed by its standard error:
```
$ ~/bin/bwtool/bwtool agg -long-form -header -expanded 0:100:0 hsAll_Cap1_all_bothAdapters.ERCC.bw ERCC.bed /dev/stdout
Segmentation fault (core dumped)
```
You can get the two input files here:
http://genome.crg.es/~jlagarde/tmp/ERCC.bed
http://genome.crg.es/~jlagarde/tmp/hsAll_Cap1_all_bothAdapters.ERCC.bw

If you could look into this issue it would be great!
Cheers

**Comment by andypohl** [comment]
I've reproduced the error, and the data looks fine to me.   It's clear though from your command what you're hoping to get.  I'm debugging.

**Comment by andypohl** [comment]
Switch the order of the parameters:
`$ ~/bin/bwtool/bwtool agg -long-form -header -expanded 0:100:0 ERCC.bed hsAll_Cap1_all_bothAdapters.ERCC.bw /dev/stdout`
A better error message than "segmentation fault" would be nice though.
