### ISSUE TITLE
bwtool disagrees with bigwig header on statistics

### ISSUE THREAD

**Issue by scottcain** [CRG-Barcelona/bwtool#63]
Hi,

Let me start with the fact that I am no expert on the BigWig file format, so it's possible that I am misunderstanding something. If that's the case, let me apologize in advance.

I am using bwtool so that I can script the extraction of statistical data from a large number of bigwig files.  On my test file (https://s3.amazonaws.com/wormbase-modencode/wiggle_binaries/snyder/Snyder_MAB5_POLII_L3_combined_WS220.bw) I ran this command:

```
~/bin/bwtool summary 10000 -total -header -with-sum-of-squares Snyder_MAB5_POLII_L3_combined_WS220.bw  Snyder_MAB5_POLII_L3_combined_WS220.bw.out
```
(as well as with several other values for loci, but it doesn't seem to make a difference) and got this result:
```
#chrom  start   end             size            num_data        min     max     mean    median  sum_of_squares
various 0       100272276       100272276       96446674        1.00    3773.00 27.04   15.00   157736882558.11
```
Using these data, I calculated the standard deviation to be sqrt(ss/N): 40.44110

When I examine the statistics produced for JBrowse reading the same file (using this URL:https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=I%3A7109135..7119384&tracks=MAB-5%20Combined%20(Pol%20II%20ChIP) and clicking on the track label to get an "about this track" option), I get these values:

```
basesCovered | 98353688
scoreMax | 3773
scoreMean | 26.701994865713626
scoreMin | 1
scoreStdDev | 40.15232163850225
scoreSum | 2626239672
scoreSumSquares | 228692531009
```
While the values for the standard deviation are similar, they are not the same, which is somewhat surprising to me.  Additionally, the sum of squares is very different but I guess that is compensated for by the fact that the number of bases covered is different too.  

Is there something I'm missing?

Thanks,
Scott

**Comment by andypohl** [comment]
I've never used JBrowse, but in the same track menu for the "About this track" is an option to download the data.  I did, but only got the data for chromosome "I".  Anyway:

```bash
tail -n +2 data.bedgraph | awk 'BEGIN{size=0;}{size = size + $2 - $1;}END{print size;}'
##14571889
```

Now suppose you have a genome-wide bed file just basically storing the chromosome lengths, and we'll call it `chroms.bed`:

```
I	0	15072423
II	0	15279345
III	0	13783700
IV	0	17493793
V	0	20924149
X	0	17718866
```

I'll reproduce what you have:

```bash
bwtool summary -header -total chroms.bed Snyder_MAB5_POLII_L3_combined_WS220.bw stdout
###chrom	start	end	size	num_data	min	max	mean	median
##various	0	100272276	100272276	96446674	1.00	3773.00	27.04	15.00
```

and expand on that a little by leaving out the `-total` option so we see the stats on each chromosome:

```bash
bwtool summary -header chroms.bed Snyder_MAB5_POLII_L3_combined_WS220.bw stdout
###chrom	start	end	size	num_data	min	max	mean	median
##I	0	15072423	15072423	14571889	1.00	3531.00	30.10	18.00
##II	0	15279345	15279345	14724494	1.00	3773.00	28.32	15.00
##III	0	13783700	13783700	13367955	1.00	1227.00	31.97	20.00
##IV	0	17493793	17493793	16679834	1.00	2923.00	25.69	14.00
##V	0	20924149	20924149	19851735	1.00	1757.00	23.47	12.00
##X	0	17718866	17718866	17250767	1.00	2352.00	24.93	15.00
```

And you'll see the `num_data` value for chromosome I jives with what I got when adding up all the bedGraph regions in my downloaded bedGraph.

I found one thing that might be the issue.  I don't know.  I invite you to download a couple more bigWig utilities from [UCSC](http://hgdownload.cse.ucsc.edu/admin/exe/), the originators of the bigWig format.  Namely the utilities called `bigWigInfo`, `bigWigToBedGraph`, and `bedGraphToBigWig`.

If you try `bigWigInfo`, you'll get that larger "basesCovered" you mentioned:

```bash
bigWigInfo Snyder_MAB5_POLII_L3_combined_WS220.bw 
##version: 3
##isCompressed: yes
##isSwapped: 0
##primaryDataSize: 64,284,915
##primaryIndexSize: 1,103,024
##zoomLevels: 8
##chromCount: 6
##basesCovered: 98,353,688
##mean: 26.701995
##min: 1.000000
##max: 3773.000000
##std: 40.152322
```

but if you convert it to bedGraph and then back to bigWig, you'll get something different:

```bash
bigWigToBedGraph Snyder_MAB5_POLII_L3_combined_WS220.bw converted.bg
cut -f1,3 chroms.bed > chroms.sizes
bedGraphToBigWig converted.bg chroms.sizes converted_back.bw
bigWigInfo converted_back.bw
##version: 4
##isCompressed: yes
##isSwapped: 0
##primaryDataSize: 59,889,874
##primaryIndexSize: 513,380
##zoomLevels: 10
##chromCount: 6
##basesCovered: 96,446,674
##mean: 27.035412
##min: 1.000000
##max: 3773.000000
##std: 40.441104
```

So I don't know what's up with that.  "version 3" versus "version 4"?  bwtool counts bases the same way in either file:

```bash
bwtool summary -header chroms.bed converted_back.bw stdout
###chrom	start	end	size	num_data	min	max	mean	median
##I	0	15072423	15072423	14571889	1.00	3531.00	30.10	18.00
##II	0	15279345	15279345	14724494	1.00	3773.00	28.32	15.00
##III	0	13783700	13783700	13367955	1.00	1227.00	31.97	20.00
##IV	0	17493793	17493793	16679834	1.00	2923.00	25.69	14.00
##V	0	20924149	20924149	19851735	1.00	1757.00	23.47	12.00
##X	0	17718866	17718866	17250767	1.00	2352.00	24.93	15.00
```

If there's something wrong about how I create `converted_back.bw`, I'm not sure what that is.

**Comment by scottcain** [comment]
Hi @andypohl 

Thanks for your input on this.  I have no clue about the different versions, but that is probably the source of the problem.  Since these aren't my data, I guess I should just go with what the file itself is reporting (and since they don't differ by that much, I don't suppose it matters which is "right" :-/

**Comment by andypohl** [comment]
I'd strongly advise against using any summary statistics that you cannot reproduce from raw data.  The original file was probably produced without any inspection to basesCovered and I wouldn't be surprised if its spent years never being questioned... the reason being, most people who need to extract the data won't leverage those stats.  A typical operation is to convert the bigWig to a wig or bedGraph because many many more bioinformatics tools are compatible with the text formats.  I think that that 98,353,688 basesCovered number is false, and any result derived from that is suspect.
